# Generated by Django 5.1.3 on 2024-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_menuitem_photo_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restock_level',
            field=models.PositiveIntegerField(default=10, verbose_name='Restock Level'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
