# Generated by Django 5.1.3 on 2024-12-01 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
